import type { ComplianceFieldDefinition } from "./contracts.js";

export const algorithmicComplianceFields: ComplianceFieldDefinition[] = [
  {
    fieldName: "agency",
    description: "Reporting agency name.",
    expectedValues: "Text",
    notes: "The data dictionary notes full agency names were standardized in 2024.",
    triggerKeywords: ["agency", "department", "office", "public schools", "dss"],
    critical: true,
  },
  {
    fieldName: "tool_name",
    description: "Tool name.",
    expectedValues: "Text",
    triggerKeywords: ["tool", "system", "model", "product", "application"],
    critical: true,
  },
  {
    fieldName: "tool_desc",
    description: "Short description of what the tool does.",
    expectedValues: "Text",
    triggerKeywords: ["does", "used for", "describes", "workflow", "function"],
    critical: true,
  },
  {
    fieldName: "purpose_type",
    description: "Category for the purpose of the tool.",
    expectedValues: "Data management, Information presentation, Performance evaluation, Resource allocation, Risk management, Triage",
    triggerKeywords: ["purpose", "triage", "risk management", "allocation", "evaluation", "presentation"],
    critical: true,
  },
  {
    fieldName: "purpose_desc",
    description: "Detailed description of how the algorithmic tool is used.",
    expectedValues: "Text",
    triggerKeywords: ["how it is used", "decision support", "used by", "workflow purpose"],
    critical: true,
  },
  {
    fieldName: "date_first_use",
    description: "Month and year of first use.",
    expectedValues: "YYYY/MM",
    triggerKeywords: ["first used", "started", "launched", "date of first use"],
  },
  {
    fieldName: "data_training",
    description: "Type and source of training data.",
    expectedValues: "Text",
    triggerKeywords: ["training data", "trained on", "model training", "historical data"],
    critical: true,
  },
  {
    fieldName: "data_input",
    description: "Type and source of input data.",
    expectedValues: "Text",
    triggerKeywords: ["input data", "ingests", "collects", "analyzes", "source data"],
    critical: true,
  },
  {
    fieldName: "data_output",
    description: "Type of data produced by the tool.",
    expectedValues: "Text",
    triggerKeywords: ["output", "produces", "score", "recommendation", "report", "label"],
    critical: true,
  },
  {
    fieldName: "identifying_info",
    description: "Whether the tool collects or analyzes identifying information.",
    expectedValues: "TRUE, FALSE",
    triggerKeywords: ["pii", "identifying information", "personal data", "name", "address", "ssn", "biometric"],
    critical: true,
  },
  {
    fieldName: "computation_type",
    description: "Category for the computation performed by the tool.",
    expectedValues: "Classification, Clustering, Data generation, Forecasting, Matching, Ranking, Sampling, Scoring",
    triggerKeywords: ["classification", "forecast", "matching", "ranking", "scoring", "prediction"],
    critical: true,
  },
  {
    fieldName: "population_type",
    description: "Population affected by the tool.",
    expectedValues: "Individuals, Property, Group/organization/business, Geographic space, Biological sample, Other",
    triggerKeywords: ["individuals", "residents", "businesses", "population", "students", "patients"],
    critical: true,
  },
  {
    fieldName: "vendor_name",
    description: "Vendor or contractor involved in the tool.",
    expectedValues: "Text, None, Not discloseable",
    triggerKeywords: ["vendor", "contractor", "third party", "supplier", "partner"],
    critical: true,
  },
  {
    fieldName: "vendor_desc",
    description: "Description of vendor involvement.",
    expectedValues: "Text",
    triggerKeywords: ["vendor involvement", "implementation support", "hosted by", "maintained by"],
  },
  {
    fieldName: "updated",
    description: "Whether the tool was updated in the past year.",
    expectedValues: "Yes, No, Created in CY20XX",
    triggerKeywords: ["updated", "retrained", "refreshed", "changed this year"],
  },
  {
    fieldName: "updated_desc",
    description: "Description of how the tool was updated.",
    expectedValues: "Text",
    triggerKeywords: ["fresh training data", "weights", "new version", "new release", "retraining"],
  },
];

export const highRiskSignals = [
  "bypass review",
  "skip review",
  "auto approve",
  "publish immediately",
  "definitely a strong buy",
  "guaranteed to go up",
  "guaranteed return",
  "make that recommendation confident",
  "do not mention uncertainty",
  "ignore uncertainty",
  "strong buy",
  "approve this budget",
  "send to production",
  "deploy now",
  "delete records",
  "share pii",
  "biometric",
  "face recognition",
  "voiceprint",
  "override policy",
];

export const googleCapabilityMap = [
  {
    capability: "Interleaved resident explanations",
    service: "Gemini on Vertex AI",
    purpose: "Turn dense algorithmic-tool records into plain-language, mixed-output explainers for NYC residents.",
    status: "active-path",
  },
  {
    capability: "Live agents and interruption",
    service: "Gemini Live API",
    purpose: "Support real-time voice interaction, interruption, and supervised multi-agent conversations.",
    status: "planned",
  },
  {
    capability: "Voice supervision",
    service: "Speech-to-Text / Text-to-Speech",
    purpose: "Convert spoken conversations to transcripts and play back supervised responses.",
    status: "adapter-ready",
  },
  {
    capability: "LLM orchestration and verification",
    service: "Vertex AI",
    purpose: "Run Gemini-based routing, extraction, monitoring, and policy verification.",
    status: "adapter-ready",
  },
  {
    capability: "Document ingestion",
    service: "Document AI",
    purpose: "Extract text and structure from uploaded PDFs and forms before monitoring.",
    status: "planned",
  },
  {
    capability: "Analytics warehouse",
    service: "BigQuery",
    purpose: "Store event telemetry, audit trails, and compliance analytics.",
    status: "planned",
  },
  {
    capability: "External agent workspace",
    service: "Agent Studio",
    purpose: "Future interface for supervised multi-agent task execution.",
    status: "planned",
  },
];
